# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1horCzAjPCzj-bIvFziZiI8QvWIepLvSd
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
from collections import Counter

root = "/content/drive/MyDrive/CellMob_AUB/CellMob"

print(os.path.exists(root))
print(os.listdir(root)[:10])

rows = []

for folder in os.listdir(root):
    folder_path = os.path.join(root, folder)
    if not os.path.isdir(folder_path):
        continue

    parts = folder.split("_")
    label = parts[0]
    city = parts[-1]

    for file in os.listdir(folder_path):
        if file.endswith(".csv"):
            rows.append({
                "folder": folder,
                "file": file,
                "city": city,
                "label": label,
                "path": os.path.join(folder_path, file)
            })

df_index = pd.DataFrame(rows)

print("Number of CSV files:", len(df_index))
print("\nCities:", sorted(df_index["city"].unique()))
print("\nLabels:", sorted(df_index["label"].unique()))
print("\nFiles per city:")
print(df_index["city"].value_counts())

print("\nFiles per label:")
print(df_index["label"].value_counts())

df_index.head()

column_counter = Counter()
file_column_counts = []

for path in df_index["path"]:
    try:
        df_tmp = pd.read_csv(path, nrows=1, low_memory=False)
        cols = list(df_tmp.columns)

        file_column_counts.append({
            "path": path,
            "n_columns": len(cols)
        })

        for c in cols:
            column_counter[c] += 1

    except Exception as e:
        print(f"Error reading {path}: {e}")

df_columns = pd.DataFrame({
    "column": list(column_counter.keys()),
    "appears_in_n_files": list(column_counter.values())
}).sort_values(by=["appears_in_n_files","column"], ascending=[False,True])

df_file_cols = pd.DataFrame(file_column_counts)

print("Total unique columns across all files:", len(df_columns))
print("\nDifferent file widths found:")
print(df_file_cols["n_columns"].value_counts().sort_index())

all_file_cols = df_columns[df_columns["appears_in_n_files"] == len(df_index)]

print("\nNumber of columns appearing in all files:", len(all_file_cols))

common_columns = all_file_cols["column"].tolist()

clean_dfs = []

for _, row in df_index.iterrows():
    try:
        df = pd.read_csv(row["path"], low_memory=False)

        # keep only columns that exist in every file
        df = df[common_columns].copy()

        # add metadata
        df["city"] = row["city"]
        df["label"] = row["label"]
        df["source_file"] = row["file"]

        clean_dfs.append(df)

    except Exception as e:
        print(f"Error processing {row['path']}: {e}")

df_all = pd.concat(clean_dfs, ignore_index=True)

print("Combined shape:", df_all.shape)
print("\nColumns:")
print(df_all.columns.tolist())

print("\nCities in combined data:")
print(df_all["city"].value_counts())

print("\nLabels in combined data:")
print(df_all["label"].value_counts())

feature_cols = [c for c in df_all.columns if c not in ["city", "label", "source_file"]]

# convert everything to numeric
for col in feature_cols:
    df_all[col] = pd.to_numeric(df_all[col], errors="coerce")

# fill missing values
df_all[feature_cols] = df_all[feature_cols].fillna(0)

print("Remaining NaNs:", df_all[feature_cols].isna().sum().sum())

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_all["label_encoded"] = le.fit_transform(df_all["label"])

print(dict(zip(le.classes_, le.transform(le.classes_))))

df_sample = df_all.sample(n=200000, random_state=42)

print(df_sample.shape)

X = df_sample[feature_cols]
y = df_sample["label_encoded"]

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier(
    n_estimators=100,
    n_jobs=-1,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

client_datasets = {}

for city in df_all["city"].unique():
    df_city = df_all[df_all["city"] == city]

    X_city = df_city[feature_cols].values
    y_city = df_city["label_encoded"].values

    client_datasets[city] = (X_city, y_city)

for city in client_datasets:
    print(city, client_datasets[city][0].shape)

from sklearn.linear_model import LogisticRegression

global_model = LogisticRegression(
    max_iter=200,
    n_jobs=-1,
    multi_class="multinomial"
)

import numpy as np

client_samples = {}
max_per_client = 100000

for city in df_all["city"].unique():
    df_city = df_all[df_all["city"] == city]

    if len(df_city) > max_per_client:
        df_city = df_city.sample(n=max_per_client, random_state=42)

    X_city = df_city[feature_cols].values.astype(np.float32)
    y_city = df_city["label_encoded"].values.astype(np.int64)

    client_samples[city] = (X_city, y_city)

for city in client_samples:
    print(city, client_samples[city][0].shape, np.unique(client_samples[city][1]))

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader
from copy import deepcopy
import numpy as np
from sklearn.metrics import classification_report, accuracy_score

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

class TMDNet(nn.Module):
    def __init__(self, input_dim=54, hidden_dim=64, num_classes=4):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.ReLU(),
            nn.Linear(hidden_dim, num_classes)
        )

    def forward(self, x):
        return self.net(x)

batch_size = 256
client_loaders = {}

for city, (X_city, y_city) in client_samples.items():
    X_tensor = torch.tensor(X_city, dtype=torch.float32)
    y_tensor = torch.tensor(y_city, dtype=torch.long)

    dataset = TensorDataset(X_tensor, y_tensor)
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    client_loaders[city] = loader

for city in client_loaders:
    print(city, len(client_loaders[city]))

df_test = df_all.sample(n=40000, random_state=42)

X_test_fl = torch.tensor(df_test[feature_cols].values.astype(np.float32), dtype=torch.float32)
y_test_fl = df_test["label_encoded"].values

def train_local(model, loader, epochs=1, lr=0.001):
    model = model.to(device)
    model.train()

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    for _ in range(epochs):
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            optimizer.zero_grad()
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            loss.backward()
            optimizer.step()

    return model.state_dict()


def fedavg_aggregate(local_states, client_sizes):
    new_state = deepcopy(local_states[0])
    total_size = sum(client_sizes)

    for key in new_state.keys():
        new_state[key] = sum(
            (client_sizes[i] / total_size) * local_states[i][key]
            for i in range(len(local_states))
        )

    return new_state


def evaluate_model(model, X_test, y_test):
    model = model.to(device)
    model.eval()

    with torch.no_grad():
        outputs = model(X_test.to(device))
        preds = torch.argmax(outputs, dim=1).cpu().numpy()

    acc = accuracy_score(y_test, preds)
    print("Accuracy:", acc)
    print(classification_report(y_test, preds))

    return acc, preds



global_model = TMDNet(input_dim=len(feature_cols), hidden_dim=64, num_classes=4).to(device)

num_rounds = 5
local_epochs = 1

for rnd in range(num_rounds):
    local_states = []
    client_sizes = []

    for city, loader in client_loaders.items():
        local_model = deepcopy(global_model)
        local_state = train_local(local_model, loader, epochs=local_epochs, lr=0.001)

        local_states.append(deepcopy(local_state))
        client_sizes.append(len(loader.dataset))

    new_global_state = fedavg_aggregate(local_states, client_sizes)
    global_model.load_state_dict(new_global_state)

    print(f"Completed FedAvg round {rnd+1}/{num_rounds}")

    acc, _ = evaluate_model(global_model, X_test_fl, y_test_fl)

def train_local_fedavg_matched(model, loader, epochs=1, lr=0.001):  ##################################test
    model = model.to(device)
    model.train()

    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)
    optimizer = optim.SGD(model.parameters(), lr=lr)

    for _ in range(epochs):
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            optimizer.zero_grad()
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            loss.backward()
            optimizer.step()

    return model.state_dict()

global_model_matched = TMDNet(input_dim=len(feature_cols), hidden_dim=64, num_classes=4).to(device)

num_rounds = 5
local_epochs = 1
fedavg_matched_accuracies = []

for rnd in range(num_rounds):
    local_states = []
    client_sizes = []

    for city, loader in client_loaders.items():
        local_model = deepcopy(global_model_matched)
        local_state = train_local_fedavg_matched(local_model, loader, epochs=local_epochs, lr=0.001)

        local_states.append(deepcopy(local_state))
        client_sizes.append(len(loader.dataset))

    new_global_state = fedavg_aggregate(local_states, client_sizes)
    global_model_matched.load_state_dict(new_global_state)

    print(f"\nCompleted matched FedAvg round {rnd+1}/{num_rounds}")
    acc, _ = evaluate_model(global_model_matched, X_test_fl, y_test_fl)
    fedavg_matched_accuracies.append(acc)











from sklearn.metrics import classification_report, accuracy_score

def evaluate_model(model, X_test, y_test):
    model = model.to(device)
    model.eval()

    with torch.no_grad():
        outputs = model(X_test.to(device))
        preds = torch.argmax(outputs, dim=1).cpu().numpy()

    acc = accuracy_score(y_test, preds)
    print("Accuracy:", acc)
    print(classification_report(y_test, preds, zero_division=0))
    return acc, preds

import pandas as pd
import torch

all_y = []
for city, (X_city, y_city) in client_samples.items():
    all_y.extend(y_city.tolist())

class_counts = pd.Series(all_y).value_counts().sort_index()
class_weights = 1.0 / class_counts
class_weights = class_weights / class_weights.sum() * len(class_weights)

class_weights_tensor = torch.tensor(class_weights.values, dtype=torch.float32).to(device)
print(class_counts)
print(class_weights_tensor)

from copy import deepcopy
import torch
import torch.nn as nn
import torch.optim as optim

def zeros_like_state_dict(state_dict):
    return {k: torch.zeros_like(v, device=device) for k, v in state_dict.items()}

def move_state_to_device(state_dict, device):
    return {k: v.clone().detach().to(device) for k, v in state_dict.items()}

def scaffold_train_local(model, loader, c_global, c_local, epochs=1, lr=0.01):
    model = deepcopy(model).to(device)
    model.train()

    criterion = nn.CrossEntropyLoss(weight=class_weights_tensor)
    optimizer = optim.SGD(model.parameters(), lr=lr)

    global_state = move_state_to_device(model.state_dict(), device)

    step_count = 0

    for _ in range(epochs):
        for X_batch, y_batch in loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)

            optimizer.zero_grad()
            outputs = model(X_batch)
            loss = criterion(outputs, y_batch)
            loss.backward()

            with torch.no_grad():
                for name, param in model.named_parameters():
                    if param.grad is not None:
                        param.grad += (c_global[name] - c_local[name])
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            step_count += 1

    local_state = move_state_to_device(model.state_dict(), device)

    new_c_local = {}
    for name in local_state:
        new_c_local[name] = c_local[name] - c_global[name] + (global_state[name] - local_state[name]) / step_count

    delta_c = {}
    for name in new_c_local:
        delta_c[name] = new_c_local[name] - c_local[name]

    return local_state, new_c_local, delta_c

def average_model_states(local_states, client_sizes):
    total_size = sum(client_sizes)
    new_state = {}

    for key in local_states[0].keys():
        new_state[key] = sum(
            (client_sizes[i] / total_size) * local_states[i][key]
            for i in range(len(local_states))
        )

    return new_state

def update_server_control(c_global, delta_cs, beta=0.25):
    num_clients = len(delta_cs)
    new_c_global = {}

    for key in c_global.keys():
        avg_delta = sum(delta_c[key] for delta_c in delta_cs) / num_clients
        new_c_global[key] = c_global[key] + beta * avg_delta

    return new_c_global

scaffold_model = TMDNet(input_dim=len(feature_cols), hidden_dim=64, num_classes=4).to(device)
scaffold_model.load_state_dict(deepcopy(global_model_matched.state_dict()))

c_global = update_server_control(c_global, delta_cs, beta=0.25)
c_locals = {city: zeros_like_state_dict(scaffold_model.state_dict()) for city in client_loaders.keys()}

print("Fresh SCAFFOLD initialized.")

num_rounds_scaffold = 10
local_epochs_scaffold = 1
lr_scaffold = 0.0005

scaffold_accuracies = []

for rnd in range(num_rounds_scaffold):
    local_states = []
    client_sizes = []
    delta_cs = []

    for city, loader in client_loaders.items():
        local_state, new_c_local, delta_c = scaffold_train_local(
            scaffold_model,
            loader,
            c_global,
            c_locals[city],
            epochs=local_epochs_scaffold,
            lr=lr_scaffold
        )

        local_states.append(local_state)
        client_sizes.append(len(loader.dataset))
        c_locals[city] = new_c_local
        delta_cs.append(delta_c)

    new_global_state = average_model_states(local_states, client_sizes)
    scaffold_model.load_state_dict(new_global_state)

    c_global = update_server_control(c_global, delta_cs)

    print(f"\nCompleted corrected SCAFFOLD round {rnd+1}/{num_rounds_scaffold}")
    acc, _ = evaluate_model(scaffold_model, X_test_fl, y_test_fl)
    scaffold_accuracies.append(acc)